spring.application.name=serviciopedido
server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/pedidos_db
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true